### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by simonft** [selwin/django-user_agents#16]
Could you release a new version? The fixes for using this with 1.10 would be particularly useful. 

Thanks!

**Comment by nikaro** [comment]
@selwin please ?

**Comment by digi0ps** [comment]
@selwin Really need the new version with the fix for middleware.

**Comment by originalankur** [comment]
@nikaro  and @digi0ps you can use this meanwhile 

$ pip install https://github.com/selwin/django-user_agents/archive/master.zip

if you are already aware kindly ignore.

**Comment by rondebu** [comment]
Replace the middleware.py source code with this, fixes the problem.

```
from django.utils.functional import SimpleLazyObject
from .utils import get_user_agent


class UserAgentMiddleware(object):

    def __init__(self, get_response=None):
        if get_response is not None:
            self.get_response = get_response

    def __call__(self, request):
        self.process_request(request)
        return self.get_response(request)

    def process_request(self, request):
        request.user_agent = SimpleLazyObject(lambda: get_user_agent(request))
```
The middleware is located in:
site-packages/django_user_agents/

**Comment by jonashaag** [comment]
bump

**Comment by tony** [comment]
... Another unmaintained project. >_<

This is really hurting people. Please someone make an official fork and we can continue there.

**Comment by selwin** [comment]
Version 0.3.2 is now on PyPI. Sorry for the delay.
