### ISSUE TITLE
support for django2.0

### ISSUE THREAD

**Issue by wenguonideshou** [selwin/django-user_agents#30]
thanks

**Comment by benzkji** [comment]
any progress on this? should not be too hard to implement? volunteers for a PR? I will, when updating many of my django CMS websites...

**Comment by benzkji** [comment]
for the reference, the PR is already there: https://github.com/selwin/django-user_agents/pull/32

**Comment by MSBPeace** [comment]
+1 for Django 2.0 support. I'd like to use this for my Django projects but all of them are 2.0

**Comment by selwin** [comment]
Fixed in https://pypi.org/project/django-user-agents/
